/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio;

import javax.swing.JOptionPane;

/**
 *
 * @author Benjamin
 */
public class Menu extends javax.swing.JFrame {
    private Inicio login;
    private Empresa gestion;
    private int contador;
    /**
     * Creates new form Menu
     */
    public Menu(Inicio login,int contador,Empresa gestion) {
        initComponents();
        this.login=login;
        this.gestion=gestion;
        this.contador=contador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnAdherido = new javax.swing.JButton();
        btnEnvio = new javax.swing.JButton();
        btnPaquete = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnVehiculo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu  Empresa Logistica");

        btnCliente.setText("Gestion clientes");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnEmpleado.setText("Gestion empleados");
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });

        btnAdherido.setText("Gestion adheridos");
        btnAdherido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdheridoActionPerformed(evt);
            }
        });

        btnEnvio.setText("Gestion Envios");
        btnEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvioActionPerformed(evt);
            }
        });

        btnPaquete.setText("Gestion paquetes");
        btnPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaqueteActionPerformed(evt);
            }
        });

        btnProducto.setText("Gestion Productos");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnReporte.setText("Gestion reportes");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnTicket.setText("Gestion tickets");
        btnTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTicketActionPerformed(evt);
            }
        });

        btnVehiculo.setText("Gestion vehiculos");
        btnVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCliente)
                            .addComponent(btnAdherido)
                            .addComponent(btnPaquete)
                            .addComponent(btnReporte)
                            .addComponent(btnVehiculo))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdherido)
                        .addGap(29, 29, 29)
                        .addComponent(btnPaquete)
                        .addGap(18, 18, 18)
                        .addComponent(btnReporte)
                        .addGap(30, 30, 30)
                        .addComponent(btnVehiculo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEmpleado)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnProducto)
                        .addGap(18, 18, 18)
                        .addComponent(btnTicket)
                        .addGap(30, 30, 30)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        if (contador >= 10){
            JOptionPane.showMessageDialog(null,"Se ha llegado al maximo cupo de errores, por consiguiente el programa se reiniciara");
            System.exit(0);
        }
        VentanaCliente ventanadatos=new VentanaCliente(this,gestion,contador);
        ventanadatos.setVisible(true);
        ventanadatos.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        if (contador >= 10){
            JOptionPane.showMessageDialog(null,"Se ha llegado al maximo cupo de errores, por consiguiente el programa se reiniciara");
            System.exit(0);
        }
        VentanaEmpleado ventanadatos=new VentanaEmpleado(this,gestion,contador);
        ventanadatos.setVisible(true);
        ventanadatos.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        login.setVisible(true);
        this.setVisible(false);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvioActionPerformed
        if (contador >= 10){
            JOptionPane.showMessageDialog(null,"Se ha llegado al maximo cupo de errores, por consiguiente el programa se reiniciara");
            System.exit(0);
        }
        VentanaEnvio ventanadatos=new VentanaEnvio(this,gestion,contador);
        ventanadatos.setVisible(true);
        ventanadatos.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnEnvioActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        if (contador >= 10){
            JOptionPane.showMessageDialog(null,"Se ha llegado al maximo cupo de errores, por consiguiente el programa se reiniciara");
            System.exit(0);
        }
        VentanaReporte ventanadatos=new VentanaReporte(this,gestion,contador);
        ventanadatos.setVisible(true);
        ventanadatos.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnAdheridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdheridoActionPerformed
        if (contador >= 10){
            JOptionPane.showMessageDialog(null,"Se ha llegado al maximo cupo de errores, por consiguiente el programa se reiniciara");
            System.exit(0);
        }
        VentanaAdherido ventanadatos=new VentanaAdherido(this,gestion,contador);
        ventanadatos.setVisible(true);
        ventanadatos.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdheridoActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        if (contador >= 10){
            JOptionPane.showMessageDialog(null,"Se ha llegado al maximo cupo de errores, por consiguiente el programa se reiniciara");
            System.exit(0);
        }
        VentanaProducto ventanadatos=new VentanaProducto(this,gestion,contador);
        ventanadatos.setVisible(true);
        ventanadatos.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        if (contador >= 10){
            JOptionPane.showMessageDialog(null,"Se ha llegado al maximo cupo de errores, por consiguiente el programa se reiniciara");
            System.exit(0);
        }
        VentanaTicket ventanadatos=new VentanaTicket(this,gestion,contador);
        ventanadatos.setVisible(true);
        ventanadatos.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaqueteActionPerformed
        if (contador >= 10){
            JOptionPane.showMessageDialog(null,"Se ha llegado al maximo cupo de errores, por consiguiente el programa se reiniciara");
            System.exit(0);
        }
        VentanaPaquete ventanadatos=new VentanaPaquete(this,gestion,contador);
        ventanadatos.setVisible(true);
        ventanadatos.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnPaqueteActionPerformed

    private void btnVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoActionPerformed
        if (contador >= 10){
            JOptionPane.showMessageDialog(null,"Se ha llegado al maximo cupo de errores, por consiguiente el programa se reiniciara");
            System.exit(0);
        }
        VentanaVehiculo ventanadatos=new VentanaVehiculo(this,gestion,contador);
        ventanadatos.setVisible(true);
        ventanadatos.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdherido;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnEnvio;
    private javax.swing.JButton btnPaquete;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTicket;
    private javax.swing.JButton btnVehiculo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
